/* pricing-data.js — SINGLE SOURCE OF TRUTH for code-side rental prices.
 *
 * WHY THIS EXISTS
 *   E-bike and Jetti walking-pole prices used to be hardcoded in ~5 places each,
 *   so one price change meant hunting through several files and they drifted.
 *   Now every *static, code-side* price display reads from the tables below.
 *   Change a price here once and every page that hydrates from it updates.
 *
 * HOW PAGES USE IT
 *   1. Grids:  <div data-price-grid="ebike"></div>  (or "jetti")
 *              → filled with the tile grid (used on trailside.html).
 *   2. Inline: <span data-price="ebike.firstHour"></span>
 *              → filled with a single value by dotted path.
 *   3. Programmatic: window.CTC_PRICING.tierListHtml('jetti')
 *              → returns the <li class="tier"> list used on pricing.html.
 *   Include with:  <script src="pricing-data.js"></script>  (before any inline
 *   script that calls window.CTC_PRICING; it self-hydrates on DOMContentLoaded).
 *
 * ⚠️ TWO PRICE COPIES LIVE OUTSIDE THIS FILE — keep them in sync by hand:
 *   • Google Sheet → Pricing / PricingTiers tabs. These drive pricing.html's
 *     MAIN e-bike cards on production (the DEFAULT_* arrays in pricing.html are
 *     only offline fallbacks). Edit the Sheet when e-bike rates change.
 *   • goodcall-knowledge.html — generated by tools/gen_knowledge_base.py. After
 *     a price change, re-run that script and commit the regenerated file.
 */
(function () {
  var P = {
    ebike: {
      firstHour: '$25',
      addlHour: '$10',
      note: '$25 for the first hour, then $10 for each additional hour.',
      tiers: [
        { dur: '1 Hour',  hours: '1 hour',              price: '$25', badge: '' },
        { dur: '2 Hours', hours: '2 hours',             price: '$35', badge: '' },
        { dur: '3 Hours', hours: '3 hours',             price: '$45', badge: '' },
        { dur: '4 Hours', hours: '4 hours · Half day', price: '$55', badge: 'Half Day' },
      ],
    },
    jetti: {
      from: '$8',
      tiers: [
        { dur: '1 Hour',  hours: '1 hour',  price: '$8',  badge: '' },
        { dur: '2 Hours', hours: '2 hours', price: '$12', badge: '' },
        { dur: '3 Hours', hours: '3 hours', price: '$15', badge: '' },
        { dur: '4 Hours', hours: '4 hours', price: '$18', badge: 'Half Day' },
      ],
    },
  };

  // Tile styles mirror the existing trailside.html price tiles exactly.
  var TILE  = 'background:#fff;border:1px solid rgba(0,0,0,.06);border-radius:6px;padding:12px 14px;text-align:center';
  var PRICE = "font-family:'Bebas Neue',sans-serif;font-size:1.4rem;color:var(--forest);letter-spacing:.03em";
  var LABEL = 'font-size:.78rem;color:#5a5a5a';

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }

  // Resolve a dotted path like "ebike.firstHour" or "jetti.tiers.0.price".
  function get(path) {
    return String(path).split('.').reduce(function (o, k) {
      return o == null ? o : o[k];
    }, P);
  }

  // Tile grid for trailside.html (data-price-grid="ebike"|"jetti").
  function gridHtml(key) {
    var g = P[key];
    if (!g) return '';
    return g.tiers.map(function (t) {
      return '<div style="' + TILE + '">' +
               '<div style="' + PRICE + '">' + esc(t.price) + '</div>' +
               '<div style="' + LABEL + '">' + esc(t.hours) + '</div>' +
             '</div>';
    }).join('');
  }

  // <li class="tier"> list for pricing.html cards (data-driven jettiCard).
  function tierListHtml(key) {
    var g = P[key];
    if (!g) return '';
    return g.tiers.map(function (t) {
      var dur = esc(t.dur) + (t.badge ? ' <span class="tier-badge">' + esc(t.badge) + '</span>' : '');
      return '<li class="tier"><span class="tier-dur">' + dur + '</span>' +
             '<span class="tier-price">' + esc(t.price) + '</span></li>';
    }).join('');
  }

  function hydrate(root) {
    var r = root || document;
    r.querySelectorAll('[data-price-grid]').forEach(function (el) {
      var html = gridHtml(el.getAttribute('data-price-grid'));
      if (html) el.innerHTML = html;
    });
    r.querySelectorAll('[data-price]').forEach(function (el) {
      var v = get(el.getAttribute('data-price'));
      if (v != null) el.textContent = v;
    });
  }

  P.gridHtml = gridHtml;
  P.tierListHtml = tierListHtml;
  window.CTC_PRICING = P;
  window.CTC_hydratePricing = hydrate;

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { hydrate(); });
  } else {
    hydrate();
  }
})();
